// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project5EMDAStaffManagement.Data;

namespace Project5EMDAStaffManagement.Migrations
{
    [DbContext(typeof(StaffDbContext))]
    partial class StaffDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Project5EMDAStaffManagement.Models.Reasons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Reason");

                    b.Property<int>("ReasonCount");

                    b.HasKey("Id");

                    b.ToTable("Reasons");
                });

            modelBuilder.Entity("Project5EMDAStaffManagement.Models.SignOuts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Day");

                    b.Property<int>("HoursIn");

                    b.Property<int?>("ReasonId");

                    b.Property<int?>("StaffNameId");

                    b.Property<DateTime>("TimeOut");

                    b.HasKey("Id");

                    b.HasIndex("ReasonId");

                    b.HasIndex("StaffNameId");

                    b.ToTable("SignOuts");
                });

            modelBuilder.Entity("Project5EMDAStaffManagement.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("TimeIn");

                    b.Property<DateTime>("TimeOut");

                    b.HasKey("Id");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("Project5EMDAStaffManagement.Models.SignOuts", b =>
                {
                    b.HasOne("Project5EMDAStaffManagement.Models.Reasons", "Reason")
                        .WithMany()
                        .HasForeignKey("ReasonId");

                    b.HasOne("Project5EMDAStaffManagement.Models.Staff", "StaffName")
                        .WithMany()
                        .HasForeignKey("StaffNameId");
                });
#pragma warning restore 612, 618
        }
    }
}
